incdec:
	nasm incdec.s -o test.bin
	ndisasm -b 64 test.bin
stack:
	nasm stack.s -o test.bin
	ndisasm -b 64 test.bin
shift:
	nasm shift.s -o test.bin
	ndisasm -b 64 test.bin
move:
	nasm move.s -o test.bin
	ndisasm -b 64 test.bin
add:
	nasm add.s -o test.bin
	ndisasm -b 64 test.bin
sub:
	nasm sub.s -o test.bin
	ndisasm -b 64 test.bin
mul:
	nasm mul.s -o test.bin
	ndisasm -b 64 test.bin
