linux:
	gcc -c agnesi.c
	rm -f main.a
	ar crs main.a agnesi.o
mac:
	clang -c agnesi.c
	rm -f main.a
	ar crs main.a agnesi.o
win:
	gcc -c agnesi.c
	rm -f main.a
	ar crs main.a agnesi.o
clean:
	rm -f *.o
