.PHONY:learn
learn:
	gcc \
	main/iterator.c \
	main/main.c \
	main/string.c \
	reading/c.c \
	reading/cpp.c \
	reading/dts.c \
	reading/include.c \
	reading/none.c \
	reading/struct.c
clean:
	rm -f *.exe *.out
	rm -f *.seed *.tree
	rm -f *.hash *.table
