.PHONY:learn
learn:
	gcc \
	0/main.c \
	0/string.c \
	0/traverse.c \
	learning/learn.c \
	learning/c.c \
	learning/count.c \
	learning/cpp.c \
	learning/dts.c \
	learning/include.c \
	learning/none.c \
	learning/struct.c \
	thinking/check.c \
	thinking/hash.c \
	-o hi.exe
clean:
	rm -f *.exe *.out
	rm -f *.seed *.tree
	rm -f *.hash *.table
