winglfw:
	g++ glfw.c -lglew32 -lglu32 -lopengl32 -lm
winglut:
	g++ glut.c -lglew32 -lfreeglut -lglu32 -lopengl32 -lm
linuxglfw:
	gcc glfw.c -lglfw -lGLEW -lGLU -lGL -lm
linuxglut:
	gcc glut.c -lglut -lGLEW -lGLU -lGL -lm
