linux:
	gcc -c circle.c
	rm -f main.a
	ar crs main.a circle.o
mac:
	clang -c circle.c
	rm -f main.a
	ar crs main.a circle.o
win:
	gcc -c circle.c
	rm -f main.a
	ar crs main.a circle.o
clean:
	rm -f *.o
