linux:
	gcc -c -fPIC -O2 anscii.c
	rm -f wrap1.a
	ar crs wrap1.a anscii.o
mac:
	clang -c -fPIC -O2 anscii.c
	rm -f wrap1.a
	ar crs wrap1.a anscii.o
win:
	gcc -c -O2 anscii.c
	rm -f wrap1.a
	ar crs wrap1.a anscii.o