#version 450
layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(binding = 0) buffer outdat {
	float _o[ ];
};
layout(binding = 1) buffer indat {
	float _x[ ];
};
layout(binding = 2) buffer weight {
	float _w[ ];
};

void main(){
	uint ix = gl_GlobalInvocationID.x;
	uint iy = gl_GlobalInvocationID.y;
	uint id = iy*4096 + ix;
	uint id2= id*4096;
	float tmp = 0.0;
	for(int j=0;j<4096;j++){
		tmp += _w[id2 + j]*_x[j];
	}
	_o[id] = tmp;
}
