all:
	gcc \
	main.c \
	library/string.c \
	library/traverse.c \
	library/worker.c \
	reading/1.c \
	reading/c.c \
	reading/count.c \
	reading/cpp.c \
	reading/dts.c \
	reading/include.c \
	reading/none.c \
	reading/struct.c \
	thinking/check.c \
	thinking/hash.c
clean:
	rm -f *.exe *.out
	rm -f *.seed *.tree
	rm -f *.hash *.table
